services:
  mongo:
    image: mongo:7
    container_name: napavi-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    command: ["--bind_ip_all"]

volumes:
  mongo_data:
